### ISSUE TITLE
Adapt STF to process decryption

### ISSUE THREAD

**Issue by fredo** [shutter-network/op-geth#2]
Reveal transactions (which can only appear at the top of the block) should be executed as follows:

1) Check that the decryption key contained in the reveal transaction is correct for the current block with respect to the current eon key.
2) Fetch the encrypted transactions for the current block from the inbox contract.
3) Decrypt those transactions. Ignore those transactions that are not decryptable or invalid.
4) Execute the valid transactions with a gas limit as specified by the inbox contract.

Still tbd is how events should be handled. Ideally, we get one event per encrypted transaction and maybe a summary event for the reveal transaction as a whole. This may be difficult to cram into the existing transaction execution interface though, so a potential alternative would be to concatenate all events into a single one.

**Comment by jannikluhn** [comment]
done
